apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ke9ptlk4e-java-springboot
  janus-idp.io/tekton: ke9ptlk4e-java-springboot
  backstage.io/kubernetes-id: ke9ptlk4e-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ke9ptlk4e-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
